version: '3.8'

services:
  gesture-vision:
    build: .
    container_name: gesture-vision
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/app
      - ./capturas:/app/capturas

    devices:
      - /dev/video0:/dev/video0
    privileged: true
