FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    docker.io \
    docker-compose \
    && rm -rf /var/lib/apt/lists/*

COPY requirements_api.txt requirements_api.txt
RUN pip install --no-cache-dir -r requirements_api.txt

COPY api /app/api

EXPOSE 8080

CMD ["python", "-m", "uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8080"]